### ISSUE TITLE
Freeze elements if drag

### ISSUE THREAD

**Issue by Xhonor** [qwqcode/CefSharpDraggableRegion#1]
Is it possible to fix the fact that during the movement of the window, all elements are freeze?

**Comment by ghost** [comment]
Hello @Xhonor I was also suffering from this, but I just found a solution:

Add _Control.CheckForIllegalCrossThreadCalls = false;_
`        public Form1()
        {
            Control.CheckForIllegalCrossThreadCalls = false;
        }
`

Modify a function _SendHandleMessage_
`
        public void SendHandleMessage()
        {
            if (InvokeRequired) { Invoke(new SafeCallDelegate(SendHandleMessage), new object[] { }); return; }
            Thread thread = new Thread(new ThreadStart(()=> SendMessage(Handle, WM_NCLBUTTONDOWN, HT_CAPTION, 0)));
            thread.Start();
        }
`

**Comment by Xhonor** [comment]
> Hello @Xhonor I was also suffering from this, but I just found a solution:
> 
> Add _Control.CheckForIllegalCrossThreadCalls = false;_
> ` public Form1() { Control.CheckForIllegalCrossThreadCalls = false; }`
> 
> Modify a function _SendHandleMessage_
> `public void SendHandleMessage() { if (InvokeRequired) { Invoke(new SafeCallDelegate(SendHandleMessage), new object[] { }); return; } Thread thread = new Thread(new ThreadStart(()=> SendMessage(Handle, WM_NCLBUTTONDOWN, HT_CAPTION, 0))); thread.Start(); }`

Great... Thank you :)
